# SPDX-FileCopyrightText: 2022 Pablo Delgado KrÃ¤mer
# SPDX-License-Identifier: MIT

name: Deploy Release

on: [workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        include:
        - name: Linux
          image: ubuntu-20.04
        - name: MacOS
          image: macos-12
        - name: Windows
          image: windows-2019

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.image }}

    steps:
    - name: Set up packages (Linux)
      if: matrix.name == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libgl1-mesa-dev libglu1-mesa-dev python3-pip qtbase5-dev-tools

    - name: Set up packages (MacOS)
      if: matrix.name == 'MacOS'
      run: |
        brew install qt
        # Build fails because system-wide packages are detected; remove them
        brew uninstall --ignore-dependencies openexr imath libpng

    - name: Install NASM (Windows)
      if: matrix.name == 'Windows'
      uses: ilammy/setup-nasm@v1

    - name: Install Python packages (Linux & Windows)
      if: matrix.name != 'MacOS'
      run: pip3 install --user PySide2 PyOpenGL

    - name: Install Python packages (MacOS)
      if: matrix.name == 'MacOS'
      run: |
        pip3 install --user PySide6 PyOpenGL
        # Add dir with pyside6-uic to PATH
        echo "$HOME/Library/Python/3.11/bin" >> $GITHUB_PATH

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Build USD (Windows)
      if: matrix.name == 'Windows'
      run: |
        # Build on C: drive because of out-of-disk-space errors on D:
        python3 build_scripts/build_usd.py --generator "Visual Studio 16 2019" --verbose --materialx --openimageio --no-examples --no-tutorials C:/INSTALL --build-args USD,"-DPXR_PYTHON_SHEBANG=\"/usr/bin/env python3\""
        echo "install_dir=C:/INSTALL" >> $GITHUB_ENV

    - name: Build USD (Linux)
      if: matrix.name == 'Linux'
      run: |
        # Force build of OIIO's idiff tool (for graphical tests which we only run on Linux)
        python3 build_scripts/build_usd.py --verbose --materialx --openimageio --no-examples --no-tutorials INSTALL --build-args USD,"-DPYSIDEUICBINARY:PATH=/usr/lib/qt5/bin/uic" OpenImageIO,"-DOIIO_BUILD_TOOLS=ON"
        echo "install_dir=$PWD/INSTALL" >> $GITHUB_ENV

    - name: Build USD (MacOS)
      if: matrix.name == 'MacOS'
      run: |
        python3 build_scripts/build_usd.py --verbose --materialx --openimageio --no-examples --no-tutorials INSTALL
        echo "install_dir=$PWD/INSTALL" >> $GITHUB_ENV

    - name: Remove redundant files
      working-directory: ${{ env.install_dir }}
      run: rm -rf build src doc share

    - name: Determine archive file name
      run: |
        PYTHON_SHORT_VERSION=$(python --version 2>&1 | grep -o "[0-9]\.[0-9]\+")
        echo "archive_file_name=USD22.11_${{ matrix.name }}_x64_Python${PYTHON_SHORT_VERSION}.tar.gz" >> $GITHUB_ENV

    - name: Create archive
      working-directory: ${{ env.install_dir }}
      run: tar -zcvf ${{ env.archive_file_name }} *

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ${{ env.install_dir }}/${{ env.archive_file_name }}
        retention-days: 1

  deploy:
    name: Deploy Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts

    - name: Deploy draft release
      uses: softprops/action-gh-release@v1
      with:
        name: "Version 22.11 with MaterialX support"
        files: |
          *.tar.gz
        fail_on_unmatched_files: true
        body: "Built for [guc](https://github.com/pablode/guc)'s and [gatling](https://github.com/pablode/gatling)'s automatic workflows."
        draft: true
